---
title: "renv test"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
                      message=FALSE,
                      warning=FALSE,
                      fig.path="plots/",
                      dev.args = list(png = list(type = "cairo")))
```

```{r}
## Data 
library(AnalystHelper)
library(reshape2)
library(plyr)
library(dataRetrieval)

## Spatial
library(sf)
library(terra)
library(EVERSpatDat)

library(downloadthis)
library(rvest)


data(LOK)
```

`r paste("Updated:",format(Sys.time(),tz="America/New_York",usetz=T,"%F %R"))`

## Including Plots

```{r pressure}
# set.seed(123)
n.val <- 500
dat <- rnorm(n.val)


plot(dat,ann=F,type="n",axes=F,ylim=c(-3,3))
points(dat,pch=21,bg="pink",lwd=0.1,col="red",cex=2)
abline(h=mean(dat))
abline(h=c(mean(dat)+sd(dat),mean(dat)-sd(dat)),lty=2,col="blue")
axis_fun(1,seq(0,n.val,n.val/5),seq(0,n.val,n.val/50),seq(0,n.val,n.val/5))
axis_fun(2,seq(-3,3,1),seq(-3,3,0.5),seq(-3,3,1))
box(lwd=1)

summary(dat)
```


```{r LOK plot}
samp.site <- st_sample(LOK,10)

plot(st_geometry(LOK),col="lightblue",bg="cornsilk",border="grey")
plot(st_geometry(samp.site),add=T,pch=21,bg="lightgreen",col="red",cex=1.5,lwd=0.1)
box(lwd=1)
```