name: Render R Markdown (Windows) - test

on:
  push:
    branches: [main]
  workflow_dispatch:
  # schedule:
    # - cron: '15,30,45 * * * *'
    
jobs:
  render:
    runs-on: windows-latest
    env:
      R_LIBS_USER: ${{ github.workspace }}/.Rlibrary
      PERSONAL_PAT: ${{ secrets.GH_PAT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Set up Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/*.R', '**/*.Rmd') }}
        restore-keys: |
           ${{ runner.os }}-R-
            
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        pak-version: "devel"
        packages: |
          rmarkdown
          knitr
          reshape2
          plyr
          dataRetrieval
          sf
          terra
          downloadthis
          rvest
          SwampThingPaul/AnalystHelper
          SwampThingPaul/EVERSpatDat

    - name: Render R Markdown
      shell: Rscript {0}
      run: |
        rmarkdown::render("test_report.Rmd")
    
    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Commit and push rendered report
      run: |
        git add -A
        git commit -m "update report" || echo "No changes to commit"
        git pull --ff-only
        git push origin || echo "No changes to commit"

# git remote set-url origin https://x-access-token:${env:PERSONAL_PAT}@github.com/${{ github.repository }}